# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7e7b751ddfe655299e526605e589e90d2277285b8640ff83769bbd64950f3307494660b8b121ee44dfe48ccce14c4c9b4d34a7f1f3efe55baaf236d469c9518

test:
  secret_key_base: 5058956d0589c3e3c4c0a6265188ef16d7535b3bebc9a793a5313d4bd478abec8e827aa16261853bdd06e5eec45f46b47e77d8a63e231b9cd403bbc13bd857f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
